
name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce it
      description: Tell us how to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Tell us the expected behavior.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us your environment.
      value: |
        - OS: [e.g. Ubuntu]
        - OS Version: [e.g. Ubuntu 24.04.2 LTS]
        - PostgreSQL Version: [e.g. 15.1]
        - PGroonga Version: [e.g. 12.1.0]
           - You can check the version by running:
               SELECT extversion FROM pg_catalog.pg_extension WHERE extname = 'pgroonga';
        - libgroonga Version: [e.g.  8.0.1]
           - You can check the version by running:
               SELECT pgroonga_command('status')::jsonb->1->'version' AS libgroonga_version;
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Tell us the additional context if you have.
    validations:
      required: false
