SRCS =						\
	src/pgroonga.c				\
	src/pgrn-column-name.c			\
	src/pgrn-command-escape-value.c		\
	src/pgrn-convert.c			\
	src/pgrn-create.c			\
	src/pgrn-ctid.c				\
	src/pgrn-escape.c			\
	src/pgrn-flush.c			\
	src/pgrn-global.c			\
	src/pgrn-groonga.c			\
	src/pgrn-groonga-tuple-is-alive.c	\
	src/pgrn-highlight-html.c		\
	src/pgrn-index-status.c			\
	src/pgrn-jsonb.c			\
	src/pgrn-keywords.c			\
	src/pgrn-match-positions-byte.c		\
	src/pgrn-match-positions-character.c	\
	src/pgrn-options.c			\
	src/pgrn-pg.c				\
	src/pgrn-query-escape.c			\
	src/pgrn-query-expand.c			\
	src/pgrn-query-extract-keywords.c	\
	src/pgrn-snippet-html.c			\
	src/pgrn-value.c			\
	src/pgrn-variables.c			\
	src/pgrn-wal.c				\
	src/pgrn-writable.c			\
	vendor/xxHash/xxhash.c
