name: Release
on:
  push:
    tags:
      - "*"
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Download artifacts
        run: |
          workflows=(package.yml windows.yml)
          for workflow in "${workflows[@]}"; do
            run_id=""
            while true; do
              echo "Waiting for run to start ${workflow}..."
              run_id=$(gh run list \
                         --branch ${GITHUB_REF_NAME} \
                         --jq '.[].databaseId' \
                         --json databaseId \
                         --repo ${GITHUB_REPOSITORY} \
                         --workflow ${workflow})
              if [ -n "${run_id}" ]; then
                break
              fi
              sleep 60
            done
            gh run watch \
              --exit-status \
              --interval 60 \
              --repo ${GITHUB_REPOSITORY} \
              ${run_id}
            gh run download ${run_id} \
              --dir release-artifacts \
              --pattern "release-*" \
              --repo ${GITHUB_REPOSITORY}
          done
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          repository: "pgroonga/pgroonga.github.io"
          path: "pgroonga.github.io"
      - name: Extract release note
        run: |
          ruby \
            -e 'print("## PGroonga "); \
                puts(ARGF.read.split(/^## /)[1]. \
                       gsub(/ {.+?}/, ""). \
                       gsub(/\[(.+?)\]\[.+?\]/) {$1})' \
            pgroonga.github.io/news/index.md > release-note.md
      - name: Publish
        run: |
          title=$(head -n1 release-note.md | sed -e 's/^## //')
          tail -n +2 release-note.md > release-note-without-version.md
          gh release create ${GITHUB_REF_NAME} \
            --discussion-category Releases \
            --notes-file release-note-without-version.md \
            --repo ${GITHUB_REPOSITORY} \
            --title "${title}" \
            release-artifacts/*/*
        env:
          GH_TOKEN: ${{ github.token }}
