name: Release
on:
  push:
    tags:
      - "*"
  pull_request:
    paths:
      - ".github/workflows/release.yml"
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Download artifacts
        if: |
          github.ref_type == 'tag'
        run: |
          workflows=(package.yml windows.yml)
          for workflow in "${workflows[@]}"; do
            run_id=""
            while true; do
              echo "Waiting for run to start ${workflow}..."
              run_id=$(gh run list \
                         --branch ${GITHUB_REF_NAME} \
                         --jq '.[].databaseId' \
                         --json databaseId \
                         --limit 1 \
                         --repo ${GITHUB_REPOSITORY} \
                         --workflow ${workflow})
              if [ -n "${run_id}" ]; then
                break
              fi
              sleep 300
            done
            gh run watch \
              --exit-status \
              --interval 300 \
              --repo ${GITHUB_REPOSITORY} \
              ${run_id}
            gh run download ${run_id} \
              --dir release-artifacts \
              --pattern "release-*" \
              --repo ${GITHUB_REPOSITORY}
          done
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/checkout@v5
        with:
          repository: "pgroonga/pgroonga.github.io"
          path: "pgroonga.github.io"
      - name: Extract release note
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ruby \
            -e 'print("## PGroonga "); \
                puts(ARGF.read.split(/^## /)[1]. \
                       gsub(/ {.+?}/, ""). \
                       gsub(/\[(.+?)\]\[.+?\]/) {$1})' \
            pgroonga.github.io/news/index.md | tee release-note.md

          previous_tag=$(gh release list \
                           --jq '.[].tagName' \
                           --json tagName \
                           --limit 1)

          echo "### Contributors" | tee -a release-note.md
          echo | tee -a release-note.md
          command_line="git shortlog -sn ${previous_tag}.."
          echo '```console' | tee -a release-note.md
          echo "\$ ${command_line}" | tee -a release-note.md
          ${command_line} | tee -a release-note.md
          echo '```' | tee -a release-note.md
      - name: Publish
        if: |
          github.ref_type == 'tag'
        run: |
          title=$(head -n1 release-note.md | sed -e 's/^## //')
          tail -n +2 release-note.md > release-note-without-version.md
          gh release create ${GITHUB_REF_NAME} \
            --discussion-category Releases \
            --notes-file release-note-without-version.md \
            --repo ${GITHUB_REPOSITORY} \
            --title "${title}" \
            release-artifacts/*/*
        env:
          GH_TOKEN: ${{ github.token }}
